package com.b2y4n.vc.sdjwt.issuer

import com.b2y4n.vc.sdjwt.crypto.Hasher
import com.b2y4n.vc.sdjwt.models.Disclosure
import com.b2y4n.vc.sdjwt.models.SdJwtConstants
import com.b2y4n.vc.sdjwt.models.ClaimPath
import java.security.SecureRandom
import java.util.Base64
import kotlinx.serialization.json.*

/**
 * Handles the recursive concealment of JSON payload elements during SD-JWT issuance.
 *
 * This class traverses the JSON payload tree, replacing claims marked for selective
 * disclosure with Base64url-encoded digest hashes in `_sd` arrays (for object properties)
 * or `{"...": "<digest>"}` wrapper objects (for array elements). It also generates
 * randomly padded decoy digests to prevent disclosure count inference attacks.
 *
 * Concealment follows the rules defined in
 * [RFC 9901 Section 5](https://www.rfc-editor.org/rfc/rfc9901.html#section-5):
 * - Object property disclosures produce 3-element arrays: `[salt, claimName, claimValue]`.
 * - Array element disclosures produce 2-element arrays: `[salt, claimValue]`.
 * - Decoy digests are randomly generated bytes of the correct hash size, indistinguishable
 *   from real disclosure digests.
 *
 * @property saltGenerator The generator used to produce cryptographically random salts for each disclosure.
 * @property hasher The hash function used to compute disclosure digests (e.g., SHA-256).
 * @property secureRandom The secure random source for generating decoy padding bytes and insertion positions.
 * @constructor Creates a [PayloadConcealer] with the specified salt generator, hasher, and random source.
 */
class PayloadConcealer(
        private val saltGenerator: SaltGenerator,
        private val hasher: Hasher,
        private val secureRandom: SecureRandom = SecureRandom()
) {
    /**
     * Recursively traverses and conceals the given [JsonElement] based on the specified
     * concealment configuration.
     *
     * For each claim path in [fieldsToConceal], the corresponding JSON property or array
     * element is replaced with its disclosure digest. Decoy digests are appended according
     * to [decoyConstraints] to obscure the true number of concealed claims.
     *
     * @param element The current [JsonElement] to evaluate. Can be a [JsonObject], [JsonArray],
     *                or a JSON primitive (primitives are returned unchanged).
     * @param currentPath The [ClaimPath] representing the current position in the JSON tree,
     *                    used for matching against concealment and decoy constraints.
     * @param fieldsToConceal The set of [ClaimPath]s identifying which claims should be
     *                        replaced with disclosure digests.
     * @param decoyConstraints A mapping from [ClaimPath] to the minimum number of digests
     *                         (real + decoy) that must appear at that path, used to pad
     *                         `_sd` arrays and array disclosure counts.
     * @param disclosures The mutable list that accumulates generated [Disclosure] objects
     *                    as they are created during traversal.
     * @return The modified [JsonElement] with concealed claims replaced by their digests.
     */
    fun conceal(
            element: JsonElement,
            currentPath: ClaimPath,
            fieldsToConceal: Set<ClaimPath>,
            decoyConstraints: Map<ClaimPath, Int>,
            disclosures: MutableList<Disclosure>
    ): JsonElement {
        return when (element) {
            is JsonObject ->
                    concealObject(
                            element,
                            currentPath,
                            fieldsToConceal,
                            decoyConstraints,
                            disclosures
                    )
            is JsonArray ->
                    concealArray(
                            element,
                            currentPath,
                            fieldsToConceal,
                            decoyConstraints,
                            disclosures
                    )
            else -> element
        }
    }

    /**
     * Conceals properties within a JSON object by replacing marked claims with digest
     * entries in the `_sd` array and optionally padding with decoy digests.
     *
     * Properties whose [ClaimPath] appears in [fieldsToConceal] are removed from the
     * object and replaced by their Base64url hash in the sorted `_sd` array. All
     * remaining properties are recursively processed for nested concealment.
     *
     * @param element The JSON object to conceal.
     * @param currentPath The [ClaimPath] of this object within the payload tree.
     * @param fieldsToConceal The set of claim paths to conceal.
     * @param decoyConstraints The minimum digest count constraints.
     * @param disclosures The accumulator for generated disclosures.
     * @return A new [JsonObject] with concealed properties replaced by the `_sd` digest array.
     */
    private fun concealObject(
            element: JsonObject,
            currentPath: ClaimPath,
            fieldsToConceal: Set<ClaimPath>,
            decoyConstraints: Map<ClaimPath, Int>,
            disclosures: MutableList<Disclosure>
    ): JsonObject {
        val modifiedMap = mutableMapOf<String, JsonElement>()
        val digests = mutableListOf<String>()

        for ((key, value) in element) {
            val newPath = currentPath.claim(key)
            val concealedValue =
                    conceal(value, newPath, fieldsToConceal, decoyConstraints, disclosures)

            if (fieldsToConceal.contains(newPath)) {
                val salt = saltGenerator.generateSalt()
                val disclosureArray = buildJsonArray {
                    add(salt)
                    add(key)
                    add(concealedValue)
                }
                val encodedDisclosure =
                        Base64.getUrlEncoder()
                                .withoutPadding()
                                .encodeToString(
                                        disclosureArray.toString().toByteArray(Charsets.UTF_8)
                                )

                disclosures.add(Disclosure(encodedDisclosure, salt, key, concealedValue, newPath))
                digests.add(hasher.hashBase64Url(encodedDisclosure))
            } else {
                modifiedMap[key] = concealedValue
            }
        }

        val minDigests = decoyConstraints[currentPath] ?: 0
        if (minDigests > digests.size) {
            val count = minDigests - digests.size
            repeat(count) {
                val dummyBytes = ByteArray(hasher.digestSizeBytes)
                secureRandom.nextBytes(dummyBytes)
                digests.add(Base64.getUrlEncoder().withoutPadding().encodeToString(dummyBytes))
            }
        }

        if (digests.isNotEmpty()) {
            val existingSd =
                    modifiedMap[SdJwtConstants.CLAIM_SD]?.jsonArray?.map {
                        it.jsonPrimitive.content
                    }
                            ?: emptyList()
            val allDigests = (existingSd + digests).sorted()
            modifiedMap[SdJwtConstants.CLAIM_SD] = JsonArray(allDigests.map { JsonPrimitive(it) })
        }
        return JsonObject(modifiedMap)
    }

    /**
     * Conceals elements within a JSON array by replacing marked items with
     * `{"...": "<digest>"}` wrapper objects and optionally inserting decoy wrappers.
     *
     * Array elements whose [ClaimPath] appears in [fieldsToConceal] are replaced
     * in-place by a single-key JSON object containing the disclosure digest.
     * Decoy wrappers are inserted at random positions to obscure the array structure.
     *
     * @param element The JSON array to conceal.
     * @param currentPath The [ClaimPath] of this array within the payload tree.
     * @param fieldsToConceal The set of claim paths to conceal.
     * @param decoyConstraints The minimum digest count constraints.
     * @param disclosures The accumulator for generated disclosures.
     * @return A new [JsonArray] with concealed elements replaced by digest wrapper objects.
     */
    private fun concealArray(
            element: JsonArray,
            currentPath: ClaimPath,
            fieldsToConceal: Set<ClaimPath>,
            decoyConstraints: Map<ClaimPath, Int>,
            disclosures: MutableList<Disclosure>
    ): JsonArray {
        val newArray = mutableListOf<JsonElement>()

        for ((index, item) in element.withIndex()) {
            val newPath = currentPath.arrayElement(index)
            val concealedValue =
                    conceal(item, newPath, fieldsToConceal, decoyConstraints, disclosures)

            if (fieldsToConceal.contains(newPath)) {
                val salt = saltGenerator.generateSalt()
                val disclosureArray = buildJsonArray {
                    add(salt)
                    add(concealedValue)
                }
                val encodedDisclosure =
                        Base64.getUrlEncoder()
                                .withoutPadding()
                                .encodeToString(
                                        disclosureArray.toString().toByteArray(Charsets.UTF_8)
                                )

                disclosures.add(Disclosure(encodedDisclosure, salt, null, concealedValue, newPath))

                val digest = hasher.hashBase64Url(encodedDisclosure)
                newArray.add(buildJsonObject { put(SdJwtConstants.ARRAY_DECOY_KEY, digest) })
            } else {
                newArray.add(concealedValue)
            }
        }

        val minDigests = decoyConstraints[currentPath] ?: 0
        val realConcealedCount =
                newArray.count {
                    it is JsonObject && it.containsKey(SdJwtConstants.ARRAY_DECOY_KEY)
                }
        if (minDigests > realConcealedCount) {
            val count = minDigests - realConcealedCount
            repeat(count) {
                val dummyBytes = ByteArray(hasher.digestSizeBytes)
                secureRandom.nextBytes(dummyBytes)
                val decoyDigestStr =
                        Base64.getUrlEncoder().withoutPadding().encodeToString(dummyBytes)
                val decoyObj = buildJsonObject {
                    put(SdJwtConstants.ARRAY_DECOY_KEY, decoyDigestStr)
                }

                val insertIndex = secureRandom.nextInt(newArray.size + 1)
                newArray.add(insertIndex, decoyObj)
            }
        }

        return JsonArray(newArray)
    }
}
